# Generated by Django 3.2.19 on 2023-12-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_permission',
            field=models.BooleanField(default=False),
        ),
    ]
